receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  kafka-telemetry:
    brokers:
      - kafka:9092
    topic: telemetry
    encoding: otlp_proto
    protocol_version: 2.0.0

  kafka-logs:
    brokers:
      - kafka:9092
    topic: logs
    encoding: otlp_proto
    protocol_version: 2.0.0
  
  kafka-metrics:
    brokers:
      - kafka:9092
    topic: metrics
    encoding: otlp_proto
    protocol_version: 2.0.0

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka-telemetry]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka-metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka-logs]
